# Generated by Django 4.0 on 2023-10-31 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='categoryField',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.category'),
        ),
    ]
